p8105_hw3_hw2851
================

## Problem 1

``` r
instacart
```

    ## # A tibble: 1,384,617 × 15
    ##    order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##       <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ##  1        1      49302                 1         1  112108 train               4
    ##  2        1      11109                 2         1  112108 train               4
    ##  3        1      10246                 3         0  112108 train               4
    ##  4        1      49683                 4         0  112108 train               4
    ##  5        1      43633                 5         1  112108 train               4
    ##  6        1      13176                 6         0  112108 train               4
    ##  7        1      47209                 7         0  112108 train               4
    ##  8        1      22035                 8         1  112108 train               4
    ##  9       36      39612                 1         0   79431 train              23
    ## 10       36      19660                 2         1   79431 train              23
    ## # … with 1,384,607 more rows, and 8 more variables: order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>, product_name <chr>,
    ## #   aisle_id <int>, department_id <int>, aisle <chr>, department <chr>

Let’s first get an overview of the dataset. The instacart dataset has
1384617 rows. It contains 15 columns: order_id, product_id,
add_to_cart_order, reordered, user_id, eval_set, order_number,
order_dow, order_hour_of_day, days_since_prior_order, product_name,
aisle_id, department_id, aisle, department. Here is the first row of the
dataset: 1, 49302, 1, 1, 112108, train, 4, 4, 10, 9, Bulgarian Yogurt,
120, 16, yogurt, dairy eggs. Here is the last row of the dataset:
3421070, 4724, 3, 1, 139822, train, 15, 6, 10, 8, Broccoli Florettes,
32, 4, packaged produce, produce. The table below shows some statistics
of the key variables: the number of orders, the number of products,
average number of products added to an order, the number of aisles and
the number of departments.

``` r
instacart %>%
  summarize(
    n_order_id = n_distinct(order_id),
    n_product_id = n_distinct(product_id),
    avg_add_to_cart_order = mean(add_to_cart_order),
    n_aisle_id = n_distinct(aisle),
    n_department = n_distinct(department_id),
  ) %>%
  knitr::kable()
```

| n_order_id | n_product_id | avg_add_to_cart_order | n_aisle_id | n_department |
|-----------:|-------------:|----------------------:|-----------:|-------------:|
|     131209 |        39123 |              8.758044 |        134 |           21 |

-   How many aisles are there, and which aisles are the most items
    ordered from? There are 134 aisles. The aisles which the most orders
    are:

``` r
instacart %>%
  count(aisle, name='n_orders') %>%
  arrange(desc(n_orders)) %>%
  filter(min_rank(desc(n_orders)) < 10) %>%
  knitr::kable()
```

| aisle                         | n_orders |
|:------------------------------|---------:|
| fresh vegetables              |   150609 |
| fresh fruits                  |   150473 |
| packaged vegetables fruits    |    78493 |
| yogurt                        |    55240 |
| packaged cheese               |    41699 |
| water seltzer sparkling water |    36617 |
| milk                          |    32644 |
| chips pretzels                |    31269 |
| soy lactosefree               |    26240 |

``` r
instacart_popular_aisles =
instacart %>%
  count(aisle, name='n_orders') %>%
  filter(n_orders > 10000)

ggplot(instacart_popular_aisles, aes(x = reorder(aisle, n_orders), y = n_orders)) +
  coord_flip() +
  geom_col(position = "dodge") +
  labs(
    title = "Number of orders for aisles with > 10k orders",
    x = "Aisle",
    y = "Number of orders"
  )
```

![](p8105_hw3_hw2851_files/figure-gfm/unnamed-chunk-4-1.png)<!-- --> The
plot above shows the number of orders for each aisle that have more than
10000 items ordered. There are 39 aisles with more than 10,000 orders.
The aisles with the most numbers of orders are fresh vegetable and fresh
fruits. They have more than 15k orders and excessively over other
aisles.

``` r
instacart %>%
  filter(aisle == c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  count(aisle, product_name, name="n_orders") %>%
  group_by(aisle) %>%
  filter(rank(desc(n_orders)) <= 3.0) %>%
  arrange(aisle, n_orders)
```

    ## # A tibble: 9 × 3
    ## # Groups:   aisle [3]
    ##   aisle                      product_name                               n_orders
    ##   <chr>                      <chr>                                         <int>
    ## 1 baking ingredients         Organic Vanilla Extract                         122
    ## 2 baking ingredients         Pure Baking Soda                                140
    ## 3 baking ingredients         Light Brown Sugar                               157
    ## 4 dog food care              Original Dry Dog                                  9
    ## 5 dog food care              Organix Chicken & Brown Rice Recipe              13
    ## 6 dog food care              Organix Grain Free Chicken & Vegetable Do…       14
    ## 7 packaged vegetables fruits Organic Blueberries                            1692
    ## 8 packaged vegetables fruits Organic Raspberries                            1920
    ## 9 packaged vegetables fruits Organic Baby Spinach                           3324

``` r
instacart %>%
  filter(product_name == c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_order_hour_of_day = mean(order_hour_of_day, digit=2)) %>%
  pivot_wider(names_from=order_dow, values_from=mean_order_hour_of_day) %>%
  knitr::kable(digits = 1)
```

    ## Warning in product_name == c("Pink Lady Apples", "Coffee Ice Cream"): longer
    ## object length is not a multiple of shorter object length

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

| product_name     |    0 |    1 |    2 |    3 |    4 |    5 |    6 |
|:-----------------|-----:|-----:|-----:|-----:|-----:|-----:|-----:|
| Coffee Ice Cream | 13.2 | 15.0 | 15.3 | 15.4 | 15.2 | 10.3 | 12.4 |
| Pink Lady Apples | 12.2 | 11.7 | 12.0 | 13.9 | 11.9 | 13.9 | 11.6 |

## Problem 2

## Problem 3
